# Generated by Django 4.2.3 on 2023-08-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast_cost", models.IntegerField(default=10)),
                ("dinner_cost", models.IntegerField(default=10)),
                ("lunch_cost", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="MessMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mess_day",
                    models.CharField(
                        choices=[
                            ("sunday", "sunday"),
                            ("monday", "monday"),
                            ("tuesday", "tuesday"),
                            ("wednesday", "wednesday"),
                            ("thursday", "thursday"),
                            ("friday", "friday"),
                            ("saterday", "saterday"),
                        ],
                        max_length=100,
                    ),
                ),
                ("breakfast", models.CharField(blank=True, max_length=254, null=True)),
                ("lunch", models.CharField(blank=True, max_length=254, null=True)),
                ("dinner", models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentMessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breakfast",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("lunch", models.BooleanField(blank=True, default=False, null=True)),
                ("dinner", models.BooleanField(blank=True, default=False, null=True)),
                ("booking_date", models.DateField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("billed_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.student",
                    ),
                ),
            ],
        ),
    ]
