# Generated by Django 4.2.3 on 2023-08-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_cost_messmenu_studentmessdetails_billmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="evening_cost",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="messmenu",
            name="evening",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="studentmessdetails",
            name="evening",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
