# Generated by Django 4.2.3 on 2023-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_cost_evening_cost_messmenu_evening_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="blood_group",
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="adhar_nu",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="caste",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="distance_from_home",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="income",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="year_of_studey",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentmessdetails",
            name="payment",
            field=models.BooleanField(default=False),
        ),
    ]
