# Generated by Django 4.2.3 on 2023-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_rename_name_student_blood_group_student_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="first_name",
            new_name="bpl",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="lastname",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone",
        ),
        migrations.AddField(
            model_name="student",
            name="admission_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="handicaped",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_sem_cgpa",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="sc_st",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="student_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
