# Generated by Django 4.2.3 on 2023-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_rename_first_name_student_bpl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="caste_certificate",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="image1",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="income_certificate",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="mark_list",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="physicaly_handicaped",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="ration_card",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="uid",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
