# Generated by Django 4.2.3 on 2023-08-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_student_caste_certificate_student_image1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
