# Generated by Django 4.2.3 on 2023-08-06 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_studentlogin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
    ]
