# Generated by Django 4.2.3 on 2023-08-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_student_adhar_nu_alter_student_admission_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmessdetails",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.studentlogin"
            ),
        ),
    ]
