# Generated by Django 4.2.3 on 2023-08-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_studentmessdetails_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billmodel",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.studentlogin"
            ),
        ),
    ]
